# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication.proto',
  package='memrl',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63ommunication.proto\x12\x05memrl\"]\n\x0b\x43ommRequest\x12\x10\n\x08last_obs\x18\x01 \x03(\x05\x12\x12\n\npre_action\x18\x02 \x01(\x05\x12\x0b\n\x03obs\x18\x03 \x03(\x05\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x0b\n\x03\x61\x64\x64\x18\x05 \x01(\x08\"\x1b\n\tCommReply\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32?\n\rCommunication\x12.\n\x04\x63omm\x12\x12.memrl.CommRequest\x1a\x10.memrl.CommReply\"\x00\x62\x06proto3'
)




_COMMREQUEST = _descriptor.Descriptor(
  name='CommRequest',
  full_name='memrl.CommRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_obs', full_name='memrl.CommRequest.last_obs', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre_action', full_name='memrl.CommRequest.pre_action', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obs', full_name='memrl.CommRequest.obs', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='memrl.CommRequest.reward', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add', full_name='memrl.CommRequest.add', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=123,
)


_COMMREPLY = _descriptor.Descriptor(
  name='CommReply',
  full_name='memrl.CommReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='memrl.CommReply.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['CommRequest'] = _COMMREQUEST
DESCRIPTOR.message_types_by_name['CommReply'] = _COMMREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommRequest = _reflection.GeneratedProtocolMessageType('CommRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMREQUEST,
  '__module__' : 'communication_pb2'
  # @@protoc_insertion_point(class_scope:memrl.CommRequest)
  })
_sym_db.RegisterMessage(CommRequest)

CommReply = _reflection.GeneratedProtocolMessageType('CommReply', (_message.Message,), {
  'DESCRIPTOR' : _COMMREPLY,
  '__module__' : 'communication_pb2'
  # @@protoc_insertion_point(class_scope:memrl.CommReply)
  })
_sym_db.RegisterMessage(CommReply)



_COMMUNICATION = _descriptor.ServiceDescriptor(
  name='Communication',
  full_name='memrl.Communication',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=154,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='comm',
    full_name='memrl.Communication.comm',
    index=0,
    containing_service=None,
    input_type=_COMMREQUEST,
    output_type=_COMMREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMUNICATION)

DESCRIPTOR.services_by_name['Communication'] = _COMMUNICATION

# @@protoc_insertion_point(module_scope)
