# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/util/grpc/policy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/util/grpc/policy.proto',
  package='memrl',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asrc/util/grpc/policy.proto\x12\x05memrl\"Z\n\x08\x41Request\x12\x10\n\x08last_obs\x18\x01 \x03(\x05\x12\x12\n\npre_action\x18\x02 \x01(\x05\x12\x0b\n\x03obs\x18\x03 \x03(\x05\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x0b\n\x03\x61\x64\x64\x18\x05 \x01(\x08\"\x18\n\x06\x41Reply\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32\x38\n\x06Policy\x12.\n\nget_action\x12\x0f.memrl.ARequest\x1a\r.memrl.AReply\"\x00\x62\x06proto3'
)




_AREQUEST = _descriptor.Descriptor(
  name='ARequest',
  full_name='memrl.ARequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_obs', full_name='memrl.ARequest.last_obs', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pre_action', full_name='memrl.ARequest.pre_action', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obs', full_name='memrl.ARequest.obs', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='memrl.ARequest.reward', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='add', full_name='memrl.ARequest.add', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=127,
)


_AREPLY = _descriptor.Descriptor(
  name='AReply',
  full_name='memrl.AReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='memrl.AReply.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['ARequest'] = _AREQUEST
DESCRIPTOR.message_types_by_name['AReply'] = _AREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ARequest = _reflection.GeneratedProtocolMessageType('ARequest', (_message.Message,), {
  'DESCRIPTOR' : _AREQUEST,
  '__module__' : 'src.util.grpc.policy_pb2'
  # @@protoc_insertion_point(class_scope:memrl.ARequest)
  })
_sym_db.RegisterMessage(ARequest)

AReply = _reflection.GeneratedProtocolMessageType('AReply', (_message.Message,), {
  'DESCRIPTOR' : _AREPLY,
  '__module__' : 'src.util.grpc.policy_pb2'
  # @@protoc_insertion_point(class_scope:memrl.AReply)
  })
_sym_db.RegisterMessage(AReply)



_POLICY = _descriptor.ServiceDescriptor(
  name='Policy',
  full_name='memrl.Policy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=155,
  serialized_end=211,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_action',
    full_name='memrl.Policy.get_action',
    index=0,
    containing_service=None,
    input_type=_AREQUEST,
    output_type=_AREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POLICY)

DESCRIPTOR.services_by_name['Policy'] = _POLICY

# @@protoc_insertion_point(module_scope)
