# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.util.grpc import policy_pb2 as src_dot_util_dot_grpc_dot_policy__pb2


class PolicyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_action = channel.unary_unary(
                '/memrl.Policy/get_action',
                request_serializer=src_dot_util_dot_grpc_dot_policy__pb2.ARequest.SerializeToString,
                response_deserializer=src_dot_util_dot_grpc_dot_policy__pb2.AReply.FromString,
                )


class PolicyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_action(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_action': grpc.unary_unary_rpc_method_handler(
                    servicer.get_action,
                    request_deserializer=src_dot_util_dot_grpc_dot_policy__pb2.ARequest.FromString,
                    response_serializer=src_dot_util_dot_grpc_dot_policy__pb2.AReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memrl.Policy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Policy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_action(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/memrl.Policy/get_action',
            src_dot_util_dot_grpc_dot_policy__pb2.ARequest.SerializeToString,
            src_dot_util_dot_grpc_dot_policy__pb2.AReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
